ALTER TABLE `Order` DROP FOREIGN KEY `Order_userId_fkey`;
ALTER TABLE `Order` MODIFY `userId` INTEGER NULL;
ALTER TABLE `Order` ADD CONSTRAINT `Order_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
